### ISSUE TITLE
sorttable_customkey is invalid HTML

### ISSUE THREAD

**Issue by avindra** [stuartlangridge/sorttable#12]
`sorttable_customkey` as an attribute name is not compliant with the HTML spec and causes issues when trying to work with React.js

Relevant react doc:

https://facebook.github.io/react/docs/jsx-gotchas.html#custom-html-attributes

A viable workaround would be to change `sorttable_customkey` to `data-value` or maybe `data-stt-value` (or something similar). React components will render valid HTML attributes and those prefixed with `data-`, but nothing else.

**Comment by stuartlangridge** [comment]
Correct. This will be fixed in the long-awaited sorttable v3. In the interim, you can fix this in your local copy by patching [lines 211 and 212](https://github.com/stuartlangridge/sorttable/blob/master/sorttable.js#L211) to say `data-sorttable-customkey` and using a `data-sorttable-customkey` attribute in your HTML.

**Comment by avindra** [comment]
Thanks. I've gone with the local patch workaround for now. Have you started work on v3 privately? If you want to work on it publicly, I'd be happy to pitch in where I can.

**Comment by stuartlangridge** [comment]
In my head, yes. Finding time to do a decent job of it is the hard thing :-)
